# Ported from https://github.com/rust-lang/rust/blob/main/rustfmt.toml
# Run rustfmt with: cargo +nightly fmt

style_edition = "2024"
use_small_heuristics = "Max"
merge_derives = false
group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_field_init_shorthand = true
